In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
# plt.style.use('ggplot')

In [16]:
# to see the full table and not only ...
pd.set_option('display.max_colwidth', -1)

In [17]:
# parses the json file into a DataFrame
# CARE pandas parses the file and sort it, its not the original order
# so first people then version and the keypoint order is also alphabetical
video1 = pd.read_json('data/example1/video_000000000001_keypoints.json')
#print(video1.head())

In [4]:
data = video1.iloc[0,0]['pose_keypoints_2d'] #compact access

In [5]:
x = data[0::3]
y = data[1::3] 
c = data[2::3]

In [6]:
print("data:\n",data)
print("x:\n",x)
print("y:\n",y)
print("confidence:\n",c)

data:
 [272.891, 116.13, 0.297799, 278.699, 139.614, 0.898033, 257.14, 143.554, 0.904758, 251.277, 178.82, 0.874795, 251.247, 208.174, 0.835583, 302.18, 135.748, 0.889571, 315.938, 172.891, 0.872779, 321.789, 206.196, 0.9027200000000001, 288.549, 206.246, 0.875929, 274.773, 208.202, 0.858062, 282.667, 249.34, 0.833213, 308.126, 276.748, 0.757915, 304.12, 204.288, 0.832992, 308.067, 251.248, 0.82598, 313.936, 292.471, 0.8022159999999999, 270.836, 114.125, 0.280363, 276.685, 112.146, 0.281618, 264.952, 116.105, 0.192547, 286.522, 112.141, 0.284722, 308.035, 304.158, 0.731127, 313.98, 302.233, 0.739961, 315.953, 296.383, 0.618895, 306.139, 294.326, 0.41984000000000005, 300.271, 292.41, 0.44876699999999997, 315.868, 278.66, 0.5016849999999999]
x:
 [272.891, 278.699, 257.14, 251.277, 251.247, 302.18, 315.938, 321.789, 288.549, 274.773, 282.667, 308.126, 304.12, 308.067, 313.936, 270.836, 276.685, 264.952, 286.522, 308.035, 313.98, 315.953, 306.139, 300.271, 315.868]
y:
 [116.13, 139.614, 14

fig, ax = plt.subplots(figsize=(5, 3))
ax.set(xlim=(-3, 3), ylim=(-1, 1))

x = np.linspace(-3, 3, 91)
t = np.linspace(1, 25, 30)
X2, T2 = np.meshgrid(x, t)
 
sinT2 = np.sin(2*np.pi*T2/T2.max())
F = 0.9*sinT2*np.sinc(X2*(1 + sinT2))

scat = ax.scatter(x[::3], F[0, ::3])
 
def animate(i):
    y_i = F[i, ::3]
    scat.set_offsets(np.c_[x[::3], y_i])
    
anim = FuncAnimation(
    fig, animate, interval=100, frames=len(t)-1)
 
plt.draw()
plt.show()

In [4]:
import sys
import time
import logging
from watchdog.observers import Observer
from watchdog.events import LoggingEventHandler


In [ ]:

logging.basicConfig(level=logging.INFO,
                        format='%(asctime)s - %(message)s',
                        datefmt='%Y-%m-%d %H:%M:%S')
path = sys.argv[1] if len(sys.argv) > 1 else '.'
event_handler = LoggingEventHandler()
observer = Observer()
observer.schedule(event_handler, path, recursive=True)
observer.start()
try:
    while True:
        time.sleep(1)
except KeyboardInterrupt:
    observer.stop()
observer.join()

In [22]:
# access data using labels
#video1.loc[ :0 , "people"]

In [23]:
# access data using index
#video1.iloc[0,0]

In [24]:
## to access the keypoints I have to convert the dict to a list 
#array = video1.as_matrix()
#
#temp= []
#werte = []
## exchange the first index to change the person
#for key, value in array[0][0].items():
#    temp = [key,value]
#    werte.append(temp)
#
## allocate the data to a variable
#pose_keypoints_2d = werte[4][1]
#print(pose_keypoints_2d)

In [9]:
d

[[0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0],
 [0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0

In [ ]:
#for i,f in enumerate(d):
#    if f:
#        d[i] = [for k,p in enumerate(f)]

In [2]:
!sudo pip install pygame

The directory '/home/martin/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/martin/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    100% |████████████████████████████████| 12.0MB 2.5MB/s ta 0:00:011


In [5]:
import sys
import time
import logging
from watchdog.observers import Observer
from watchdog.events import LoggingEventHandler
from watchdog.events import PatternMatchingEventHandler  

In [5]:
class MyHandler(PatternMatchingEventHandler):
    patterns = ["*.json"]
    data = []

    def process(self, event):
        """
        event.event_type 
            'modified' | 'created' | 'moved' | 'deleted'
        event.is_directory
            True | False
        event.src_path
            path/to/observed/file
        """
        # the file will be processed there
        try:
            #print(i)
            f = pd.read_json(event.src_path).iloc[0,0]['pose_keypoints_2d']
            self.data.append(f)
            print(f)
        except ValueError:
            print("ERROR reading: ",event.src_path, event.event_type)


    def on_created(self, event):
        self.process(event)
        
observer = Observer()
observer.schedule(MyHandler(), '.')
observer.start()

try:
    while True:
        time.sleep(1)
except KeyboardInterrupt:
    observer.stop()
observer.join()

NameError: name 'PatternMatchingEventHandler' is not defined

In [34]:
logging.basicConfig(level=logging.INFO,
                        format='%(asctime)s - %(message)s',
                        datefmt='%Y-%m-%d %H:%M:%S')
path = '.'
event_handler = LoggingEventHandler()
observer = Observer()
observer.schedule(event_handler, path, recursive=True)
observer.start()
try:
    while True:
        time.sleep(1)
except KeyboardInterrupt:
    observer.stop()
observer.join()

2018-12-03 21:26:13 - Created file: ./t
2018-12-03 21:26:13 - Modified directory: .
2018-12-03 21:26:25 - Deleted file: ./t
2018-12-03 21:26:25 - Modified directory: .


In [5]:
import pandas as pd
import numpy as np
import itertools
import os
import random

# read finished Data; case training
def readData(src):
    dataseries = []
    for i in itertools.count():
        try:
            #print(i)
            dataseries.append(np.array(pd.read_json(src+ '/'+os.path.basename(src[:-4])+'_'+str(i).zfill(12)+'_keypoints.json').iloc[0,0]['pose_keypoints_2d']))
        except ValueError:
            break
        except IndexError:
            dataseries.append(np.zeros(25*3))
    return dataseries,i

In [6]:
src = 'data/output/rennen/VID_20181204_114615.mp4'
print(src+ '/'+os.path.basename(src[:-4]))
d,_ = readData(src)

data/output/rennen/VID_20181204_114615.mp4/VID_20181204_114615


In [7]:
d

[array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 

In [8]:
labelNames=['rennen','laufen']
dataPaths=['data/output/rennen/','data/output/laufen/']
samplePaths=[]
data=[]
labels=[]

dirs0 = os.listdir(dataPaths[0])
for p in dirs0:
    samplePaths.append(dataPaths[0]+p+'0')
dirs1 = os.listdir(dataPaths[1])
for p in dirs1:
    samplePaths.append(dataPaths[1]+p+'1')


random.shuffle(samplePaths)
#print(samplePaths)
for smp in samplePaths:
    l = smp[-1:]
    smp = smp[:-1]
    td, i = readData(smp)
    i -= i%10
    data.append(td[:i])
    for _ in range(i//10):
        if l == '0':
            labels.append([1,0])
        elif l == '1':
            labels.append([0,1])
        else:
            #labels.append([[0,0] for _ in range(i)])
            print(smp)
        
print("data loaded.")
#data = data[0]
#labels = labels[0]
    


data loaded.


In [9]:
labels

[[0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [1, 0],
 [1, 0],
 [1, 0],
 [1, 0],
 [1, 0],
 [1, 0],
 [1, 0],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 

In [11]:
d = []
for s in data:
    for f in s:
        d.append(f.tolist())

In [12]:
#[len(data[i]) for i in range(45)]

In [13]:
FlatData = [item for sublist in data for item in sublist]
len(FlatData)
#FlatData[0]
temp_data =[]
for p in range(0,len(FlatData),10):
    temp_data.append(np.array(FlatData[p:p+10]).tolist())
temp_data[0][0]

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0]

In [14]:
test_data = FlatData[:100]
test_labels = labels[:100]
train_data = FlatData[100:]
train_labels = labels[100:]

In [13]:
#import tensorflow as tf

In [14]:
#data = tf.placeholder(tf.float32, [None, 10,75])
#target = tf.placeholder(tf.float32, [None, 2])

In [15]:
#num_hidden = 300
#cell = tf.nn.rnn_cell.LSTMCell(num_hidden,state_is_tuple=True)

In [16]:
#val, state = tf.nn.dynamic_rnn(cell, data, dtype=tf.float32)

In [22]:
import pygame

# Initialize Pygame.
pygame.init()
# Set size of pygame window.
screen=pygame.display.set_mode((640,480))
# Create empty pygame surface.
background = pygame.Surface(screen.get_size())
# Fill the background white color.
background.fill((255, 255, 255))
# Convert Surface object to make blitting faster.
background = background.convert()
# Copy background to screen (position (0, 0) is upper left corner).
screen.blit(background, (0,0))
# Create Pygame clock object.
clock = pygame.time.Clock()

mainloop = True
# Desired framerate in frames per second. Try out other values.
FPS = 30
# How many seconds the "game" is played.
playtime = 0.0

count = 0.0

speed = 1.0

while mainloop:
    # Do not go faster than this framerate.
    milliseconds = clock.tick(FPS*speed)
    playtime += milliseconds / 1000.0
    
    for event in pygame.event.get():
        # User presses QUIT-button.
        if event.type == pygame.QUIT:
            mainloop = False
        elif event.type == pygame.KEYDOWN:
            # User presses ESCAPE-Key
            if event.key == pygame.K_ESCAPE:
                mainloop = False

    # Print framerate and playtime in titlebar.
    text = "FPS: {0:.2f}   Playtime: {1:.2f}".format(clock.get_fps(), playtime)
    pygame.display.set_caption(text)
    background.fill((255, 255, 255))
    f = d[int(count)%len(d)]
    for i in range(0,len(f),3):
        
        confColor = 255 - int(255*f[i+2])
        #pygame.draw.rect(background, (confColor, confColor, confColor), (int(f[i]),int(f[i+1]),4,4)) #bw
        pygame.draw.rect(background, (confColor, 0, 255-confColor), (int(f[i]),int(f[i+1]),4,4)) #rb
    screen.blit(background, (300-f[8*3],300-f[8*3+1]))
    
    #Update Pygame display.
    pygame.display.flip()
    
    count += 1

# Finish Pygame.
pygame.quit()

# At the very last:
print("This game was played for {0:.2f} seconds".format(playtime))


pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
This game was played for 219.98 seconds


In [1]:
import tensorflow as tf
from tensorflow.contrib import rnn

In [2]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("/tmp/data/", one_hot=True)


Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use urllib or similar directly.
Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting /tmp/data/train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting /tmp/data/train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting /tmp/data/t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting /tmp/data/t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from t

In [4]:
batch_x,batch_y=mnist.train.next_batch(batch_size=2)
print(batch_x)
print(batch_y)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]


In [16]:
#import mnist dataset
#from tensorflow.examples.tutorials.mnist import input_data
#mnist=input_data.read_data_sets("/tmp/data/",one_hot=True)


#define constants
#unrolled through 28 time steps
time_steps=1#30
#hidden LSTM units
num_units=128
#rows of 28 pixels
n_input=75#25*3
#learning rate for adam
learning_rate=0.001
#mnist is meant to be classified in 10 classes(0-9).
n_classes=2
#size of batch
batch_size=1

In [17]:
#weights and biases of appropriate shape to accomplish above task
out_weights=tf.Variable(tf.random_normal([num_units,n_classes]))
out_bias=tf.Variable(tf.random_normal([n_classes]))

#defining placeholders
#input image placeholder
x=tf.placeholder("float",[None,time_steps,n_input])
#input label placeholder
y=tf.placeholder("float",[None,n_classes])

In [18]:
#processing the input tensor from [batch_size,n_steps,n_input] to "time_steps" number of [batch_size,n_input] tensors
input=tf.unstack(x ,time_steps,1)

In [19]:
#defining the network
lstm_layer=tf.nn.rnn_cell.LSTMCell(num_units,forget_bias=1)
outputs,_=rnn.static_rnn(lstm_layer,input,dtype="float32")

In [20]:
#converting last output of dimension [batch_size,num_units] to [batch_size,n_classes] by out_weight multiplication
prediction=tf.matmul(outputs[-1],out_weights)+out_bias

In [21]:
#loss_function
loss=tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=prediction,labels=y))
#optimization
opt=tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(loss)

#model evaluation
correct_prediction=tf.equal(tf.argmax(prediction,1),tf.argmax(y,1))
accuracy=tf.reduce_mean(tf.cast(correct_prediction,tf.float32))

In [22]:
init_op = tf.initialize_all_variables()
sess = tf.Session()
sess.run(init_op)

no_of_batches = int(len(train_data)/batch_size)
epoch = 600
for i in range(epoch):
    ptr = 0
    for j in range(no_of_batches):
        inp, out = train_data[ptr:ptr+batch_size], train_labels[ptr:ptr+batch_size]
        ptr+=batch_size
        sess.run(opt,{x: inp, y: out})
    print( "Epoch - ",str(i))
incorrect = sess.run(error,{data: test_data, target: test_labels})
print('Epoch {:2d} error {:3.1f}%'.format(i + 1, 100 * incorrect))
sess.close()

Instructions for updating:
Use `tf.global_variables_initializer` instead.


ValueError: Cannot feed value of shape (1, 75) for Tensor 'Placeholder:0', which has shape '(?, 1, 75)'

In [23]:
#initialize variables
init=tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    no_of_batches = int(len(train_data)/batch_size)
    ptr = 0
    for j in range(no_of_batches):
        inp, out = train_data[ptr:ptr+batch_size], test_labels[ptr:ptr+batch_size]
        print(j)
        print(inp, out)
        ptr+=batch_size
        #sess.run(minimize,{data: inp, target: out})
        inp = np.array(inp)
        #batch_x,batch_y=mnist.train.next_batch(batch_size=batch_size)

        inp=inp.reshape((batch_size,time_steps,n_input))

        sess.run(opt, feed_dict={x: inp, y: out})

        if iter %10==0:
            acc=sess.run(accuracy,feed_dict={x:batch_x,y:batch_y})
            los=sess.run(loss,feed_dict={x:batch_x,y:batch_y})
            print("For iter ",iter)
            print("Accuracy ",acc)
            print("Loss ",los)
            print("__________________")

        iter=iter+1

0
[array([3.50234e+02, 2.44557e+02, 9.48542e-01, 3.69909e+02, 2.65508e+02,
       8.19421e-01, 3.65959e+02, 2.65472e+02, 6.86456e-01, 3.62042e+02,
       2.99400e+02, 6.56034e-02, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       3.72481e+02, 2.66727e+02, 8.54888e-01, 3.63353e+02, 3.08475e+02,
       8.26610e-01, 3.41181e+02, 3.38490e+02, 8.60885e-01, 3.67254e+02,
       3.30741e+02, 7.82930e-01, 3.60680e+02, 3.29465e+02, 8.21093e-01,
       3.50278e+02, 3.71233e+02, 8.89885e-01, 3.50288e+02, 4.16879e+02,
       8.45194e-01, 3.71211e+02, 3.33341e+02, 8.05528e-01, 3.71238e+02,
       3.81585e+02, 8.77898e-01, 3.81659e+02, 4.24695e+02, 8.71812e-01,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 3.51621e+02, 2.40630e+02,
       8.42364e-01, 0.00000e+00, 0.00000e+00, 0.00000e+00, 3.62061e+02,
       2.44508e+02, 9.04397e-01, 3.62016e+02, 4.32463e+02, 8.52397e-01,
       3.69801e+02, 4.33811e+02, 8.18911e-01, 3.89405e+02, 4.31218e+02,
       7.87306e-01, 3.30755e+02, 4.20781e+02, 8.10869e-01, 3.

TypeError: unsupported operand type(s) for %: 'builtin_function_or_method' and 'int'

In [23]:
no_of_batches

7090

In [27]:
#calculating test accuracy
test_data = mnist.test.images[:128].reshape((-1, time_steps, n_input))
test_label = mnist.test.labels[:128]
print("Testing Accuracy:", sess.run(accuracy, feed_dict={x: test_data, y: test_label}))

RuntimeError: Attempted to use a closed Session.